version: '3.8'

services:
    nodejs: 
      build: 
         context: .
         dockerfile: Dockerfile
      ports: 
         - "3000:3000"
      volumes: 
         - ./src:/usr/src
         - ./package.json:/usr/package.json
      command: bash -c "npm install && npm start:docker"
      depends_on: 
         - postgres
      env_file: 
         - .env
      networks: 
          - app-network
    postgres:
      image: postgres:15.0
      ports: 
         - "5432:5432"
      volumes: 
         - pgdata:/var/lib/postgresql/data
      networks: 
         - app-network
      environment: 
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: city_watch

networks:
    app-network:
        driver: bridge

volumes:
    pgdata: